version: "3"

services:
  apache: 
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile
    container_name: apache
    ports:
      - 3000:80
    volumes:
      - ./src:/src
    working_dir: /src
