version: "3"

services:
  apache: 
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile
    container_name: apache
    ports:
      - 3000:80
    volumes:
      - ./src:/src
    working_dir: /src
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel-db
    
    volumes: 
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d

volumes:
  db-store: